plugin {
    dynamic-cursors {
        enabled = true
        mode = stretch # Choices: rotate, tilt, stretch, none
        threshold = 2
        
        # Optional: Shake to find (magnifies cursor when moved fast)
        shake {
            enabled = true
            threshold = 5.0
            magnification = 2.0
            duration = 500
        }
    }
}
plugin {
    hyprglass {
        enabled = 1
        default_theme = dark
        default_preset = default

        # Adjust these to your liking
        brightness = 0.9
        dark:brightness = 0.82
        
        # Example custom preset
        preset = name:alacritty-glass, glass_opacity:0.8, blur_strength:2.0
    }
}
plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = center current # [center/first] [current/all]
    }
}

# Bind to toggle the expo view
bind = SUPER CTRL ALT, TAB, hyprexpo:expo, toggle
