# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/plugins.conf
# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
exec-once = nwg-dock-hyprland -d -x -p bottom -i 55 -mb 10 -c "nwg-drawer -ft WhiteSur-light -is 35 -ovl -c 5 -spacing 25"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "WhiteSur-light"
blurls = nwg-dock-hyprland
blurls = nwg-drawer
layerrule = blur on, match:namespace nwg-drawer
layerrule = blur on, match:namespace nwg-dock-hyprland
layerrule = blur on, ignore_alpha 0.1, match:namespace nwg-drawer
# In hyprland.conf
misc {
    enable_swallow = true
    swallow_regex = ^(Alacritty|alacritty)$
    # Prevent btop-float from being swallowed so it can float freely
    swallow_exception_regex = ^(btop-float)$
}
# Unified rule for btop
windowrule = match:class ^(btop-float)$, float on, center on, size 80% 80%
# Apply glass effect to btop-float
# Explicitly use the full pavucontrol class
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on, center on, size 800 600
windowrule = match:class ^(omarchy-launch-wifi)$, float on, center on, size 80% 80%
# = Source for hyprviz
source = ./hyprviz.conf
# This stops the dock from pushing your windows around
# Corrected syntax for v0.53+
# Force the dock to the bottom layer so it stays behind windows
windowrule = match:class ^(Alacritty)$, tag hyprglass
windowrule = match:class ^(waybar)$, tag hyprglass
windowrule = match:class ^(nwg-dock-hyprland)$, tag hyprglass
